platform :ios, ‘9.0’

target ‘Betit’ do

use_frameworks!

pod 'Alamofire'
pod 'AlamofireObjectMapper'
pod ‘TPKeyboardAvoiding’
pod 'KRProgressHUD'
pod 'SCrypto'
pod 'SimpleAlert'

 target 'BetitTests' do
  inherit! :search_paths
 end		
end
